console.log("Hello, world!");

const myAge = 25; // Number
console.log(myAge);
const myName = "Ionela"; // String
const mySurname = "Dobre";
const fullName = `${myName} ${mySurname}`;
console.log(myName);
console.log(fullName);

const Female = true; // boolean
console.log(Female);

const Ionela = {
    name: "Ionela",
    age: "29",
    city: "Bucharest"
};

console.log(Ionela);
console.log(Ionela.name);

/* alert("Continut cu impact puternic emotional!"); 

const aiPeste18Ani = confirm("Ai peste 18 ani?");

const review = prompt("Lasa o recenzie!");
console.log(review);
*/

console.log(myName[5]);
console.log("Lenghth" , myName.length);

console.log("toUpperCase", fullName.toUpperCase());

console.log("indexOf", myName.indexOf("I"));
console.log("includes", fullName.includes("ela"));
console.log("endsWith", myName.endsWith("a"));
console.log("replace", fullName.replace("a", "i"));
console.log("slice", fullName.slice(0, myName.length - 1));


const a = 2;
const b = 4;
console.log("a + b =", a + b);
console.log("a - b =", a - b);
const c = a + b;
console.log("c =", c);

const d = 8;
console.log("a * d =", a * d);

const e = 8;
console.log("d : e =", d / e);

let age = 30;
age += 1; // age = age + 1 sau age++
console.log("age", age);





